apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hw-order.fullname" . }}
data:
  DB_URI: {{ printf "jdbc:postgresql://%s:%s/%s?%s"  (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase .Values.postgresql.postgresqlSchema | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword }}
  DB_SCHEMA: {{ .Values.postgresql.postgresqlSchema }}
  BILLING_SERVER: {{ .Values.billingservice.name }}
  BILLING_SERVER_USER: {{ .Values.billingservice.user }}
  BILLING_SERVER_WITHDRAW: {{ .Values.billingservice.withdraw }}
  NOTIFICATION_SERVER: {{ .Values.notificationservice.name }}
