server:
  port: ${SERVICE_PORT:8001}

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://localhost:5432/notification?currentSchema=public}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123}
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
#  jpa:
#    hibernate:
#      ddl-auto: update

management:
  port: 80
  endpoint:
    health:
      probes:
        enabled: true
